workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Grant execute permission for Gradle
        script: chmod +x ./gradlew

      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
